# Specify the line length that the printer will wrap on.
printWidth: 128

# Print trailing commas wherever possible when multi-line (A single-line array, for example, never gets trailing commas).
trailingComma: "all"
